---
title: "Contact"
description-meta: "Contact Peter Kapec, PhD"
title-block-banner: false
---

## Get in Touch

Feel free to reach out for research collaboration, student supervision inquiries, or academic questions.

### Office Information

**Peter Kapec, PhD**
Assistant Professor

Institute of Applied Informatics

Faculty of Informatics and Information Technologies (FIIT) Slovak University of Technology in Bratislava

**Office:** Room 4.30
**Address:** Ilkovičova 2, 842 16 Bratislava 4, Slovak Republic
**Email:** peter.kapec@stuba.sk

### Office Hours

**Wednesday: 13:00 - 14:00**

Please feel free to drop by during office hours or send an email to schedule an appointment at another time.

### Location

Faculty of Informatics and Information Technologies
Slovak University of Technology in Bratislava
Ilkovičova 2
842 16 Bratislava 4
Slovak Republic

---

## Research Collaboration

I am always interested in:
- Collaborating on research projects related to software visualization and data mining
- Supervising bachelor and master thesis projects
- Discussing potential PhD opportunities
- Academic partnerships and joint research initiatives
